### ISSUE TITLE
ipv6不能更新，只更新了IPV4

### ISSUE THREAD

**Issue by zhou1050** [beeyev/Mikrotik-Duckdns-Dynamic-IP-Updater#2]
请支持IPV6

**Comment by beeyev** [comment]
English please

**Comment by zhou1050** [comment]
Can it support IPV6

**Comment by zhou1050** [comment]
I can't use ipv4 here, only IPV6 can be used.

**Comment by beeyev** [comment]
okay, I will try to implement this feature soon

**Comment by zhou1050** [comment]
thank you for your help

**Comment by beeyev** [comment]
Okay, I have updated the script but could not check if it works because I don't have IPv6 connection.
Follow the instruction how to run the script and set [variable](https://github.com/beeyev/Mikrotik-Duckdns-Dynamic-IP-Updater/blob/a4587d120652e2caf7876e707fae0690b6c4ec38/mikrotik-duckdns-dynamic-ip-updater.rsc#L20) `ipv6mode` to true.
Like this:
`:local ipv6mode true;`

Please tell me if it works.

https://github.com/beeyev/Mikrotik-Duckdns-Dynamic-IP-Updater/blob/a4587d120652e2caf7876e707fae0690b6c4ec38/mikrotik-duckdns-dynamic-ip-updater.rsc#L20

**Comment by zhou1050** [comment]
Or did you only update IPv4, but not IPv6

**Comment by zhou1050** [comment]
![image](https://user-images.githubusercontent.com/46239492/120945255-f6711900-c76a-11eb-94a8-a8d76cef3ca6.png)

**Comment by zhou1050** [comment]
ipv6 still cannot be used

**Comment by zhou1050** [comment]
Are you up yet?

**Comment by zhou1050** [comment]
Do you have a telegram id？

**Comment by zhou1050** [comment]
telegram id  801065983
